name: "Build and Test"

on:
  push:
    branches: ['master', 'testBuild']

permissions:
  contents: read

jobs:
  build-java-17:
    runs-on: ubuntu-latest
    permissions:
      contents: read  
      pull-requests: read
    timeout-minutes: 130
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up JDK 17
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Apache Maven
        run: mvn -U clean install -Djava.awt.headless=true -fae -B
      - name: Copy jars
        run: mkdir staging && cp **/target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          path: staging
